name: Swift iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'

    - name: Build iOS project
      run: |
        xcodebuild -project HalalAI.xcodeproj \
           -scheme HalalAI \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
           clean build

    - name: Run tests
      run: |
        xcodebuild test \
           -project HalalAI.xcodeproj \
           -scheme HalalAI \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
           -enableCodeCoverage YES \
           | xcpretty
