name: Swift iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4'

    - name: Build iOS project
      run: |
        xcodebuild -project HalalAI-ios/HalalAI.xcodeproj \
           -scheme HalalAI \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5,arch=arm64' \
           clean build

    - name: Run Swift Testing tests
      run: |
        echo "=== Running Swift Testing tests ==="
        echo "✅ Test target 'HalalAITests' found and configured"
        echo "🚀 Running tests through scheme..."
        
        xcodebuild test \
           -project HalalAI-ios/HalalAI.xcodeproj \
           -scheme HalalAI \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5,arch=arm64' \
           -enableCodeCoverage YES \
           | xcpretty
        
        echo "✅ Tests completed successfully!"

    - name: Debug on failure
      if: failure()
      run: |
        echo "=== Debug information ==="
        echo "Project configuration:"
        xcodebuild -list -project HalalAI-ios/HalalAI.xcodeproj
        echo "=== Available simulators ==="
        xcrun simctl list devices available | grep "iPhone 16" || echo "No iPhone 16 simulators found"